Repository hugo-sid/hugo-blog-awesome, pull requests merged in 2023-06, with the labels that each got.

#55 fix: resolve theme toggle race condition
  assets/js/theme.js
Labels: size/s

#54 chore(main): release 1.2.4
  CHANGELOG.md
Labels: autorelease: pending, size/xs, Stale

#57 Update README.md
  README.md
Labels: size/xs

#60 chore(README): add websites using this theme
  README.md
Labels: size/xs

#59 chore(main): release 1.2.5
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#61 Update list of websites using this theme
  README.md
Labels: size/xs

#62 chore(main): release 1.2.6
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#64 Move tableOfContents sectin to correct part of config
  exampleSite/config.toml
Labels: size/xs

#65 chore(main): release 1.2.7
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#66 chore(main): release 1.3.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#67 Fix deprecated Twitter post format
  exampleSite/content/posts/rich-content/index.md
Labels: size/xs

#69 Add forgejo icon
  layouts/partials/svgs/svgs.html
Labels: size/xs

#70 chore(main): release 1.4.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#71 adding bskdany.com to the readme
  README.md
Labels: size/xs

#72 chore(main): release 1.4.1
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#73 Update list of websites using this theme
  README.md
Labels: size/xs

#74 chore(main): release 1.4.2
  CHANGELOG.md
Labels: autorelease: pending, size/xs
