Repository hugo-sid/hugo-blog-awesome, pull requests merged in 2023-09, with the labels that each got.

#110 Added my website to websites using hugo-blog-awesome to README
  README.md
Labels: size/xs

#108 chore(main): release 1.9.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#116 Update README.md to add my website
  README.md
Labels: size/xs

#114 chore(main): release 1.10.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#127 Multilanguage support with example included and language selector in …
  exampleSite/config.toml
  exampleSite/content/en/.DS_Store
  exampleSite/content/en/_index.md
  exampleSite/content/en/pages/about.md
  exampleSite/content/en/posts/_index.md
  exampleSite/content/en/posts/emoji-support/index.md
  exampleSite/content/en/posts/markdown-syntax/1.jpg
  exampleSite/content/en/posts/markdown-syntax/index.md
  exampleSite/content/en/posts/math-typesetting/index.md
  exampleSite/content/en/posts/placeholder-text/index.md
  exampleSite/content/en/posts/rich-content/index.md
  exampleSite/content/en/posts/table-of-content/index.md
  exampleSite/content/it/.DS_Store
  exampleSite/content/it/_index.md
  exampleSite/content/it/pages/about.md
  exampleSite/content/it/posts/_index.md
  exampleSite/content/it/posts/emoji-support/index.md
  exampleSite/content/it/posts/markdown-syntax/1.jpg
  exampleSite/content/it/posts/markdown-syntax/index.md
  exampleSite/content/it/posts/math-typesetting/index.md
  exampleSite/content/it/posts/placeholder-text/index.md
  exampleSite/content/it/posts/rich-content/index.md
  exampleSite/content/it/posts/table-of-content/index.md
  i18n/en-gb.yaml
  i18n/en-us.yaml
  i18n/it.yaml
  layouts/404.html
  layouts/_default/single.html
  layouts/index.html
  layouts/partials/footer.html
  layouts/partials/header.html
  layouts/partials/postCard.html
  layouts/partials/svgs/home.svg
  theme.toml
Labels: size/xl

#124 chore(main): release 1.11.0
  CHANGELOG.md
Labels: autorelease: pending, size/s
