Repository hugo-sid/hugo-blog-awesome, pull requests merged in 2023-10, with the labels that each got.

#131 Fix: Language Selector accessibility
  layouts/partials/header.html
Labels: size/xs

#134 ci: update GitHub access token for release please
  .github/workflows/release.yml
Labels: size/xs, Stale

#138 Add parameter to open ToC
  exampleSite/config.toml
  exampleSite/content/en/posts/table-of-content/index.md
  layouts/_default/single.html
Labels: size/xs

#132 chore(main): release 1.12.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs
