Repository hugo-sid/hugo-blog-awesome, pull requests merged in 2023-07, with the labels that each got.

#79 Feat/logo change
  README.md
  assets/icons/book-icon-dark.svg
  assets/icons/book-icon-light.svg
Labels: size/xs

#81 Feat/update favicons
  assets/icons/android-chrome-192x192.png
  assets/icons/android-chrome-512x512.png
  assets/icons/apple-touch-icon.png
  assets/icons/book-icon-dark.svg
  assets/icons/book-icon-light.svg
  assets/icons/favicon-16x16.png
  assets/icons/favicon-32x32.png
  assets/icons/favicon.ico
  assets/icons/favicon.svg
  assets/icons/mstile-144x144.png
  assets/icons/mstile-150x150.png
  assets/icons/mstile-310x150.png
  assets/icons/mstile-310x310.png
  assets/icons/mstile-70x70.png
  assets/icons/safari-pinned-tab.svg
Labels: size/s

#82 chore: Update README.md - add contributors
  README.md
Labels: size/xs

#80 chore(main): release 1.5.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#83 fix: make specifying date optional
  exampleSite/content/pages/about.md
  layouts/_default/single.html
Labels: size/xs

#84 chore(main): release 1.5.1
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#86 Update _miscellaneous.scss - fadein keyframe
  assets/sass/_miscellaneous.scss
Labels: size/xs

#85 Fix enforced defaultColor
  layouts/index.html
Labels: size/xs

#87 chore(main): release 1.5.2
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#88 Fixed bug for bold titles in header
  layouts/partials/header.html
Labels: size/xs

#89 chore(main): release 1.5.3
  CHANGELOG.md
Labels: autorelease: pending, size/xs
