Repository hugo-sid/hugo-blog-awesome, pull requests merged in 2023-08, with the labels that each got.

#96 Update svgs.html with IRC and health check icons
  layouts/partials/svgs/svgs.html
Labels: size/xs

#98 chore(main): release 1.6.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#100 add social icon for nostr
  layouts/partials/svgs/svgs.html
Labels: size/xs

#102 feat: add config for Dev containers
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: size/m

#101 chore(main): release 1.7.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#104 feat: include `_custom.scss` to facilitate quick and simple CSS adjustments #93
  assets/sass/_custom.scss
  assets/sass/main.scss
Labels: size/xs

#105 chore: update logo alt text
  README.md
Labels: size/xs

#103 chore(main): release 1.8.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#107 Fix: logo not displaying in readme
  README.md
Labels: size/xs
