Repository hugo-sid/hugo-blog-awesome, pull requests merged in 2023-05, with the labels that each got.

#30 chore(main): release 1.0.0
  CHANGELOG.md
Labels: autorelease: pending, size/l

#31 chore(main): release 1.0.1
  CHANGELOG.md
Labels: autorelease: pending, size/m

#33 chore(main): release 1.0.2
  CHANGELOG.md
Labels: autorelease: pending, size/m

#34 feat: add go to top button
  README.md
  assets/js/goToTop.js
  assets/sass/_dark.scss
  assets/sass/_goToTop.scss
  assets/sass/main.scss
  exampleSite/config.toml
  layouts/partials/footer.html
  layouts/partials/head.html
  layouts/partials/scriptsBodyEnd.html
  layouts/partials/svgs/arrowUp.svg
Labels: size/l

#35 chore(main): release 1.1.0
  CHANGELOG.md
Labels: autorelease: pending, size/s

#25 fix: handle relative non-root baseURL
  assets/icons/android-chrome-192x192.png
  assets/icons/android-chrome-512x512.png
  assets/icons/apple-touch-icon-precomposed.png
  assets/icons/apple-touch-icon.png
  assets/icons/browserconfig.xml
  assets/icons/favicon-16x16.png
  assets/icons/favicon-32x32.png
  assets/icons/favicon.ico
  assets/icons/favicon.svg
  assets/icons/mstile-144x144.png
  assets/icons/mstile-150x150.png
  assets/icons/mstile-310x150.png
  assets/icons/mstile-310x310.png
  assets/icons/mstile-70x70.png
  assets/icons/safari-pinned-tab.svg
  assets/icons/site.webmanifest
  assets/sass/_fonts.scss
  exampleSite/config.toml
  layouts/partials/browserconfig.html
  layouts/partials/head.html
  layouts/partials/header.html
  layouts/partials/webmanifest.html
  static/images/favicon/android-chrome-192x192.png
  static/images/favicon/android-chrome-512x512.png
  static/images/favicon/apple-touch-icon.png
  static/images/favicon/browserconfig.xml
  static/images/favicon/favicon-16x16.png
  static/images/favicon/favicon-32x32.png
  static/images/favicon/favicon.ico
  static/images/favicon/mstile-150x150.png
  static/images/favicon/safari-pinned-tab.svg
  static/images/favicon/site.webmanifest
Labels: size/xl

#37 chore(main): release 1.1.1
  CHANGELOG.md
Labels: autorelease: pending, size/s

#41 chore(main): release 1.1.2
  CHANGELOG.md
Labels: autorelease: pending, size/s

#44 feat: add comments partial
  README.md
  exampleSite/config.toml
  layouts/_default/single.html
  layouts/partials/comments.html
Labels: size/m

#43 chore(main): release 1.2.0
  CHANGELOG.md
Labels: autorelease: pending, size/m

#38 Add baseURL variable on See all posts button
  layouts/index.html
Labels: size/s

#48 chore(main): release 1.2.1
  CHANGELOG.md
Labels: autorelease: pending, size/m

#39 fix: refactor js code
  assets/js/goToTop.js
  assets/js/main.js
  assets/js/theme.js
  assets/js/themeLoader.js
  assets/js/themeSwitchnMenu.js
  exampleSite/config.toml
  layouts/partials/scriptsBodyEnd.html
  layouts/partials/scriptsBodyStart.html
  layouts/partials/webmanifest.html
Labels: size/xl

#49 chore(main): release 1.2.2
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#53 chore(main): release 1.2.3
  CHANGELOG.md
Labels: autorelease: pending, size/xs
