Repository hugo-sid/hugo-blog-awesome, pull requests merged in 2024-03, with the labels that each got.

#164 add my blog :-)
  README.md
Labels: size/xs

#166 Fix disqus deprecation warning
  .gitignore
  README.md
  exampleSite/hugo.toml
  layouts/partials/comments.html
  netlify.toml
Labels: size/xs

#168 Bump KaTeX to latest version 0.16.9
  exampleSite/content/de/posts/math-typesetting/index.md
  exampleSite/content/en/posts/math-typesetting/index.md
  exampleSite/content/it/posts/math-typesetting/index.md
  exampleSite/content/ru/posts/math-typesetting/index.md
  layouts/partials/helpers/katex.html
Labels: size/xs

#167 Fix typos
  CHANGELOG.md
  exampleSite/hugo.toml
Labels: size/xs

#170 Fixes paginator issue since hugo v0.123.0
  exampleSite/content/de/posts/rich-content/index.md
  exampleSite/content/en/posts/rich-content/index.md
  exampleSite/content/it/posts/rich-content/index.md
  exampleSite/content/ru/posts/rich-content/index.md
  layouts/partials/meta/post.html
  netlify.toml
Labels: size/xs

#173 fix: RSS link on post pages, closes #160
  exampleSite/hugo.toml
Labels: size/xs

#169 Add instructions on how to use the theme as hugo module
  README.md
  exampleSite/content/de/posts/emoji-support/index.md
  exampleSite/content/de/posts/table-of-content/index.md
  exampleSite/content/en/posts/emoji-support/index.md
  exampleSite/content/en/posts/table-of-content/index.md
  exampleSite/content/it/posts/emoji-support/index.md
  exampleSite/content/it/posts/table-of-content/index.md
  exampleSite/content/ru/posts/emoji-support/index.md
  exampleSite/content/ru/posts/table-of-content/index.md
  exampleSite/go.mod
  exampleSite/go.sum
  exampleSite/hugo-blog-awesome.work
  exampleSite/hugo.toml
  go.mod
  layouts/partials/head.html
  netlify.toml
Labels: size/m

#175 chore: change Discussions to GitHub discussions
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
Labels: size/xs

#161 chore(main): release 1.14.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#179 add stackshare.io svg icon
  README.md
  layouts/partials/svgs/svgs.html
Labels: size/xs
