Repository hugo-sid/hugo-blog-awesome, pull requests merged in 2024-12, with the labels that each got.

#261 added my personal site to readme
  README.md
Labels: size/xs

#263 fix: corrected French translations in Markdown guide and i18n file
  exampleSite/content/fr/posts/markdown-syntax/index.md
  exampleSite/hugo.toml
  i18n/fr-fr.yaml
Labels: size/m

#264 chore: update devcontainer.json
  .devcontainer/devcontainer.json
Labels: size/xs

#251 chore(main): release 1.19.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs
