Repository hugo-sid/hugo-blog-awesome, pull requests merged in 2024-10, with the labels that each got.

#244 feat: support user-supplied <head> html
  README.md
  layouts/partials/head.html
Labels: size/xs

#241 feat(i18n): add French translation
  exampleSite/content/fr/_index.md
  exampleSite/content/fr/pages/about.md
  exampleSite/content/fr/posts/_index.md
  exampleSite/content/fr/posts/emoji-support/index.md
  exampleSite/content/fr/posts/markdown-syntax/1.jpg
  exampleSite/content/fr/posts/markdown-syntax/index.md
  exampleSite/content/fr/posts/math-typesetting/index.md
  exampleSite/content/fr/posts/placeholder-text/index.md
  exampleSite/content/fr/posts/rich-content/index.md
  exampleSite/content/fr/posts/table-of-content/index.md
  exampleSite/hugo.toml
  i18n/fr-fr.yaml
Labels: size/xl

#246 chore(main): release 1.18.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs
