Repository hugo-sid/hugo-blog-awesome, pull requests merged in 2024-09, with the labels that each got.

#228 fix: Change line when inline code is long
  assets/sass/_code.scss
Labels: size/xs

#230 chore(main): release 1.16.1
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#233 added pt-br translation
  README.md
  exampleSite/content/br/_index.md
  exampleSite/content/br/pages/about.md
  exampleSite/content/br/posts/_index.md
  exampleSite/content/br/posts/emoji-support/index.md
  exampleSite/content/br/posts/markdown-syntax/1.jpg
  exampleSite/content/br/posts/markdown-syntax/index.md
  exampleSite/content/br/posts/math-typesetting/index.md
  exampleSite/content/br/posts/placeholder-text/index.md
  exampleSite/content/br/posts/rich-content/index.md
  exampleSite/content/br/posts/table-of-content/index.md
  exampleSite/hugo.toml
  i18n/pt-br.yaml
Labels: size/xl

#237 added journeytolunar.com
  README.md
Labels: size/xs

#234 fix: date on post is not following dateFormat
  layouts/_default/single.html
Labels: size/xs

#214 feat: svg support
  layouts/partials/bio.html
Labels: size/xs

#236 chore(main): release 1.17.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs
