Repository hugo-sid/hugo-blog-awesome, pull requests merged in 2025-03, with the labels that each got.

#285 Add Radicle SVG
  layouts/partials/svgs/svgs.html
Labels: size/xs

#284 fix: align author image display size & actual size
  layouts/partials/bio.html
Labels: size/xs

#281 add: blog.crisweb.com as using this theme
  README.md
Labels: size/xs

#282 fix: off-centre author avatars
  layouts/partials/bio.html
Labels: size/xs

#268 chore(main): release 1.19.1
  CHANGELOG.md
Labels: autorelease: pending, size/xs

#290 add my site to the readme list + remove several that no longer use the theme
  README.md
Labels: size/xs

#294 Add LeetCode (leetcode.com) social icon
  README.md
  layouts/partials/svgs/svgs.html
Labels: size/xs

#293 Add Calendly (calendly.com) social icon
  README.md
  layouts/partials/svgs/svgs.html
Labels: size/xs

#291 feat: Add Chinese language
  README.md
  exampleSite/content/zh/_index.md
  exampleSite/content/zh/pages/about.md
  exampleSite/content/zh/posts/_index.md
  exampleSite/content/zh/posts/emoji-support/index.md
  exampleSite/content/zh/posts/markdown-syntax/1.jpg
  exampleSite/content/zh/posts/markdown-syntax/index.md
  exampleSite/content/zh/posts/math-typesetting/index.md
  exampleSite/content/zh/posts/placeholder-text/index.md
  exampleSite/content/zh/posts/rich-content/index.md
  exampleSite/content/zh/posts/table-of-content/index.md
  exampleSite/hugo.toml
  i18n/zh-cn.yaml
Labels: size/xl

#292 chore(main): release 1.20.0
  CHANGELOG.md
Labels: autorelease: pending, size/xs
